export const TECHNOLOGY_URL = {
  tailwind: "https://tailwindcss.com/",
  chackraUI: "https://chakra-ui.com/",
  next: "https://nextjs.org/",
  reactQuery:
    "https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/",
  reactHoockForm: "https://react-hook-form.com/",
  reactTable:
    "https://tanstack.com/table/v8/?from=reactTableV7&original=https://react-table-v7.tanstack.com/",
  react: "https://es.reactjs.org/",
  reactHelmet: "https://github.com/nfl/react-helmet#readme",
  axios: "https://axios-http.com/",
  webpack: "https://webpack.js.org/",
  daisyUI: "https://daisyui.com/",
  javaScript: "https://developer.mozilla.org/es/docs/Web/JavaScript",
  css: "https://developer.mozilla.org/es/docs/Web/CSS",
  yup: "https://www.npmjs.com/package/yup",
  reactRouter: "https://reactrouter.com/en/main",
  zustand: "https://github.com/pmndrs/zustand",
  HTML: "https://developer.mozilla.org/es/docs/Web/HTML",
};

export const TECHNOLOGY_NAME = {
  tailwind: "Tailwind",
  chackraUI: "Chakra UI",
  next: "Next",
  reactQuery: "React query",
  reactHoockForm: "React hook form",
  reactTable: "React table",
  react: "React",
  reactHelmet: "React helmet",
  axios: "Axios",
  webpack: "Webpack",
  daisyUI: "Daisy UI",
  javaScript: "JavaScript",
  css: "CSS",
  yup: "Yup",
  reactRouter: "React router",
  zustand: "Zustand",
  HTML: "HTML",
};
